### ISSUE TITLE
Denied authorization to download the software

### ISSUE THREAD

**Issue by AlessiaSoncino** [cengels/skywriter#27]
.

**Comment by cengels** [comment]
I'm afraid I don't know what you mean. Skywriter is not a text analysis tool, nor is it currently available for download. I also don't know what "using Microsoft" means. Microsoft is a company. You can't "use" it. Well, unless you're a stakeholder, I suppose.

I saw that you opened another issue in a different repository—did you perhaps open this issue in the wrong repository? If not, you'll have to clarify what you mean exactly.
